### ISSUE TITLE
ERROR with self-contained output

### ISSUE THREAD

**Issue by CedricMidoux** [davidcarayon/quarto-inrae-extension#4]
Hello David,
Thank you very much for your template. It is very useful for our slides.

I observed some errors that seem to be linked but I did not find the origin (perhaps `self_contained`) :

* chalkboard doesn't work (`ERROR: Reveal plugin 'RevealChalkboard is not compatible with self-contained output`)
* youtube [social embeds](https://github.com/sellorm/quarto-social-embeds) fail
* `{.fragment .highlight-red}`

I finally fixed that by adding `self-contained: false` in my header.
Do you have an opinion on these problems?

Thanks again for your work!

**Comment by davidcarayon** [comment]
Hi Cedric, 
Thank you for your feedback.

It does seem that defaulting to `self_contained: true` can have some problems and the user should be the one to choose whether or not it needs his presentation to be self_contained (email sharing for example). I guess that indeed some plugins and network related features such as YouTube will fail with a self_contained document.

[This commit](https://github.com/davidcarayon/quarto-inrae-extension/commit/aad1e7638a2c7b15e66bf41189df0acad03d50eb) fixes that.

Thank you !
