### ISSUE TITLE
2 suggestions for the doc

### ISSUE THREAD

**Issue by holtzy** [davidcarayon/quarto-inrae-extension#9]
Hi!

First of all, awesome work. Having everyone at Inrae using the same style for their report would be awesome.

I would like to make 2 suggestions for the GitHub repo:

- Add a link to an online html report made using the extension
- Add a code chunk showing how the YAML header should look like

Thanks for your work!

**Comment by davidcarayon** [comment]
Hi Yan !

Thank you very much for the feedback. I didn't reply straight away because I was working on a new major version of the extension (just published right now). 

I took your suggestions into account for this new version. Hope you will find the extension has much improved.

Thank you !
